name: "DWS_TapPC游戏在线人数日计算"
type: db
db:
  type: sqlite
  path: "crawler.db"
  query: >
    SELECT
      today.crawled_at as crawled_at,
      today.online_players as today_total_online_players,
      yesterday.online_players as yesterday_total_online_players,
      ago_7.online_players as ago_7_total_online_players,
      ago_30.online_players as ago_30_total_online_players,
      ago_90.online_players as ago_90_total_online_players,
      ago_365.online_players as ago_365_total_online_players
    FROM
      (SELECT 
        crawled_at,
        online_players
      FROM
        dws_tmp_taptap_peak_players_hourly
      WHERE
        substr(crawled_at, 1, 10) = '{today}') today
    LEFT JOIN
      dws_tmp_taptap_peak_players_hourly as yesterday
    ON
      substr(datetime(today.crawled_at || ':00', '-1 day'), 1, 13) = {yesterday}
    LEFT JOIN
      dws_tmp_taptap_peak_players_hourly as ago_7
    ON
      substr(datetime(today.crawled_at || ':00', '-7 day'), 1, 13) = {days_ago:7}
    LEFT JOIN
      dws_tmp_taptap_peak_players_hourly as ago_30
    ON
      substr(datetime(today.crawled_at || ':00', '-30 day'), 1, 13) = {days_ago:30}
    LEFT JOIN
      dws_tmp_taptap_peak_players_hourly as ago_90
    ON
      substr(datetime(today.crawled_at || ':00', '-90 day'), 1, 13) = {days_ago:90}
    LEFT JOIN
      dws_tmp_taptap_peak_players_hourly as ago_365
    ON
      substr(datetime(today.crawled_at || ':00', '-365 day'), 1, 13) = {days_ago:365}
trigger_type: system
schedule: "15 * * * *"
outputs:
  - target_table: "dws_taptap_peak_players_hourly"
    table_schema:
      columns:
        - name: id
          type: INTEGER
          constraint: PRIMARY KEY AUTOINCREMENT
        - name: today_total_online_players
          type: INTEGER
        - name: yesterday_total_online_players
          type: INTEGER
        - name: ago_7_total_online_players
          type: INTEGER
        - name: ago_30_total_online_players
          type: INTEGER
        - name: ago_90_total_online_players
          type: INTEGER
        - name: ago_365_total_online_players
          type: INTEGER
        - name: crawled_at
          type: TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H', 'now', 'localtime'))
      indexes:
        - name: idx_uk_dws_taptap_pc_peak_online_players_crawled_at
          columns: [crawled_at]
          unique: true
    parser:
      type: sdk_mapping
      fields:
        - name: today_total_online_players
          source: today_total_online_players
          to_number: true   
        - name: yesterday_total_online_players
          source: yesterday_total_online_players
          to_number: true     
        - name: ago_7_total_online_players
          source: ago_7_total_online_players
          to_number: true
        - name: ago_30_total_online_players
          source: ago_30_total_online_players
          to_number: true
        - name: ago_90_total_online_players
          source: ago_90_total_online_players
          to_number: true
        - name: ago_365_total_online_players
          source: ago_365_total_online_players
          to_number: true
        - name: crawled_at
          source: crawled_at
