name: "DWS_TapPC游戏在线人数分布ListType计算"
type: db
db:
  type: sqlite
  path: "crawler.db"
  query: >
    SELECT
      a.crawled_at as crawled_at,
      CASE WHEN a.app_id = 0 THEN '在线人数<=100' ELSE b.app_name END as app_name,
      a.online_players as online_players,
      "all" as list_type
    FROM
        (SELECT
          crawled_at,
          app_id,
          SUM(online_players) as online_players
        FROM(
          SELECT 
            crawled_at,
            CASE WHEN online_players > '100' THEN app_id ELSE 0 END AS app_id,
            online_players
          FROM
            taptap_pc_online_players
          WHERE crawled_at = strftime('%Y-%m-%d %H', 'now', 'localtime'))
          GROUP BY crawled_at, app_id) a
    LEFT JOIN 
        (SELECT * FROM taptap_pc_played_ids_daily 
          WHERE crawled_at = strftime('%Y-%m-%d', 'now', 'localtime')
        ) b
    ON
    a.app_id = b.app_id
    UNION ALL
    SELECT
      a.crawled_at as crawled_at,
      b.app_name as app_name,
      a.online_players as online_players,
      b.list_type as list_type
    FROM(
      SELECT 
        crawled_at,
        app_id,
        online_players
      FROM
        taptap_pc_online_players
      WHERE crawled_at = strftime('%Y-%m-%d %H', 'now', 'localtime')) a
    LEFT JOIN 
        (SELECT * FROM taptap_pc_played_ids_daily 
          WHERE crawled_at = strftime('%Y-%m-%d', 'now', 'localtime')
        ) b
    ON
    a.app_id = b.app_id
trigger_type: system
schedule: "18 */2 * * *"
outputs:
  - target_table: "dws_taptap_pc_source_games_online_players"
    table_schema:
      columns:
        - name: id
          type: INTEGER
          constraint: PRIMARY KEY AUTOINCREMENT
        - name: app_name
          type: TEXT
        - name: list_type
          type: TEXT
        - name: online_players
          type: INTEGER
        - name: crawled_at
          type: TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H', 'now', 'localtime'))
      indexes:
        - name: idx_uk_dws_taptap_pc_source_games_online_players_crawled_at
          columns: [crawled_at, list_type, app_name]
          unique: true
    parser:
      type: sdk_mapping
      fields:
        - name: app_name
          source: app_name
        - name: list_type
          source: list_type
        - name: online_players
          source: online_players
          to_number: true      
        - name: crawled_at
          source: crawled_at
