name: "DWS_TapTap热门游戏基础信息聚合"
type: db
db:
  type: sqlite
  path: "crawler.db"
  query: >
    SELECT 
      app_id, crawled_at, app_name, distribution_type, tag_1, tag_2, tag_3 
    FROM
      (SELECT * FROM
        (SELECT 
          app_id,
          substr(crawled_at, 1, 7) as crawled_at,
          distribution_type,
          "pc" as refer,
          app_name,
          tag_1,
          tag_2,
          tag_3
        FROM taptap_pc_hot_list_hourly 
        WHERE app_id IS NOT NULL
        GROUP BY app_id, substr(crawled_at, 1, 7)) as t1
        UNION ALL
        SELECT * FROM
        (SELECT 
          app_id,
          substr(crawled_at, 1, 7) as crawled_at,
          distribution_type,
          "app" as refer,
          app_name,
          tag_1,
          tag_2,
          tag_3
        FROM taptap_app_hot_list_hourly
        WHERE app_id IS NOT NULL
        GROUP BY app_id, substr(crawled_at, 1, 7)) as t2)
      GROUP BY app_id, crawled_at, app_name, distribution_type, tag_1, tag_2, tag_3
trigger_type: system
schedule: "22 * * * *"
outputs:
  - target_table: "dws_taptap_game"
    table_schema:
      columns:
        - name: id
          type: INTEGER
          constraint: PRIMARY KEY AUTOINCREMENT
        - name: app_id
          type: INTEGER
        - name: app_name
          type: TEXT
        - name: distribution_type
          type: INTEGER
        - name: tag_1
          type: TEXT
        - name: tag_2
          type: TEXT
        - name: tag_3
          type: TEXT
        - name: crawled_at
          type: TEXT NOT NULL DEFAULT (strftime('%Y-%m', 'now', 'localtime'))
      indexes:
        - name: idx_uk_dws_taptap_game_app_id_crawled_at
          columns: [crawled_at, app_id]
          unique: true
    parser:
      type: sdk_mapping
      fields:
        - name: app_id
          source: app_id
          to_number: true      
        - name: app_name
          source: app_name
        - name: distribution_type
          source: distribution_type
          to_number: true
        - name: tag_1
          source: tag_1
        - name: tag_2
          source: tag_2
        - name: tag_3
          source: tag_3
        - name: crawled_at
          source: crawled_at
