name: "DWS_TapApp关键词广告排名计算任务"
depends_on:
  - "DWS_TapApp关键词广告每日计算任务"
type: db
db:
  type: sqlite
  path: "crawler.db"
  query: >
    SELECT
      *
    FROM(
      SELECT
        "daily" as rank_type,
        "discover" as kv_source,
        crawled_at,
        keyword,
        discover_ad_views as ad_views,
        ROW_NUMBER() OVER (PARTITION BY crawled_at ORDER BY discover_ad_views DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE crawled_at = strftime('%Y-%m-%d', 'now', 'localtime')
      UNION ALL
      SELECT
        "weekly" as rank_type,
        "discover" as kv_source,
        strftime('%Y-%W', crawled_at)  AS crawled_at,
        keyword,
        SUM(discover_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%W', crawled_at) ORDER BY SUM(discover_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%W', crawled_at) = strftime('%Y-%W', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%W', crawled_at)
      UNION ALL
      SELECT
        "monthly" as rank_type,
        "discover" as kv_source,
        strftime('%Y-%m', crawled_at)  AS crawled_at,
        keyword,
        SUM(discover_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%m', crawled_at) ORDER BY SUM(discover_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%m', crawled_at) = strftime('%Y-%m', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%m', crawled_at)
      UNION ALL
      SELECT
        "daily" as rank_type,
        "hot_search" as kv_source,
        crawled_at,
        keyword,
        hot_search_ad_views as ad_views,
        ROW_NUMBER() OVER (PARTITION BY crawled_at ORDER BY hot_search_ad_views DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE crawled_at = strftime('%Y-%m-%d', 'now', 'localtime')
      UNION ALL
      SELECT
        "weekly" as rank_type,
        "hot_search" as kv_source,
        strftime('%Y-%W', crawled_at)  AS crawled_at,
        keyword,
        SUM(hot_search_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%W', crawled_at) ORDER BY SUM(hot_search_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%W', crawled_at) = strftime('%Y-%W', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%W', crawled_at)
      UNION ALL
      SELECT
        "monthly" as rank_type,
        "hot_search" as kv_source,
        strftime('%Y-%m', crawled_at)  AS crawled_at,
        keyword,
        SUM(hot_search_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%m', crawled_at) ORDER BY SUM(hot_search_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%m', crawled_at) = strftime('%Y-%m', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%m', crawled_at)
      UNION ALL
      SELECT
        "daily" as rank_type,
        "hot_spot" as kv_source,
        crawled_at,
        keyword,
        hot_spot_ad_views as ad_views,
        ROW_NUMBER() OVER (PARTITION BY crawled_at ORDER BY hot_spot_ad_views DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE crawled_at = strftime('%Y-%m-%d', 'now', 'localtime')
      UNION ALL
      SELECT
        "weekly" as rank_type,
        "hot_spot" as kv_source,
        strftime('%Y-%W', crawled_at)  AS crawled_at,
        keyword,
        SUM(hot_spot_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%W', crawled_at) ORDER BY SUM(hot_spot_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%W', crawled_at) = strftime('%Y-%W', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%W', crawled_at)
      UNION ALL
      SELECT
        "monthly" as rank_type,
        "hot_spot" as kv_source,
        strftime('%Y-%m', crawled_at)  AS crawled_at,
        keyword,
        SUM(hot_spot_ad_views) AS ad_views,
        ROW_NUMBER() OVER (PARTITION BY strftime('%Y-%m', crawled_at) ORDER BY SUM(hot_spot_ad_views) DESC) AS ad_views_rank
      FROM dws_taptap_app_keywords_ad_daily
      WHERE strftime('%Y-%m', crawled_at) = strftime('%Y-%m', 'now', 'localtime')
      GROUP BY keyword, strftime('%Y-%m', crawled_at)
    ) a
    WHERE ad_views_rank <= 5
trigger_type: system
schedule: "21 * * * *"
outputs:
  - target_table: "dws_taptap_app_keywords_ad_rank"
    table_schema:
      columns:
        - name: rank_type
          type: TEXT
        - name: kv_source
          type: TEXT
        - name: keyword
          type: TEXT
        - name: ad_views
          type: INTEGER
        - name: ad_views_rank
          type: INTEGER
        - name: crawled_at
          type: TEXT NOT NULL
      indexes:
        - name: idx_uk_dws_taptap_app_keywords_ad_rank_rank_type_kv_source_crawled_at_ad_views_rank
          columns: [rank_type, kv_source, crawled_at, ad_views_rank]
          unique: true
    parser:
      type: sdk_mapping
      fields:
        - name: rank_type
          source: rank_type
        - name: kv_source
          source: kv_source
        - name: keyword
          source: keyword
        - name: ad_views
          source: ad_views
          to_number: true 
        - name: ad_views_rank
          source: ad_views_rank
          to_number: true    
        - name: crawled_at
          source: crawled_at
