name: "API 快速开始"
type: api
trigger_type: user
method: GET
url: "https://jsonplaceholder.typicode.com/posts/1"
outputs:
  - target_table: "taptap_pc_ad_load"
    table_schema:
      columns:
        - name: id
          type: INTEGER
          constraint: PRIMARY KEY AUTOINCREMENT
        - name: app_id
          type: INTEGER
        - name: is_ad
          type: TEXT
        - name: pos
          type: INTEGER
        - name: crawled_at
          type: TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d', 'now', 'localtime'))
      indexes:
        - name: idx_post_id
          columns: [post_id]
          unique: true
    parser:
      type: json
      fields:
        - name: app_id
          path: app_id
          to_number: true
        - name: is_ad
          path: is_ad
        - name: pos
          path: pos
