name: TaptapPC热门游戏下载榜采集任务NEW
type: api
method: GET
trigger_type: user
iterate:
  - var_name: "from"
    values:
      - 0       
      - 10 
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100
url: https://www.taptap.cn/webapiv2/pc-game/v1/list?from={from}&limit=10&type=hot&X-UA=V%3D1%26PN%3DWebApp%26LANG%3Dzh_CN%26VN_CODE%3D100000000%26LOC%3DCN%26PLT%3DPC%26DS%3DAndroid%26UID%3D9a6ce663-b36b-4427-a991-b59918a2bd0b%26OS%3DWindows%26OSV%3D10%26DT%3DPC
outputs:
- target_table: taptap_pc_hot_list_ids_hourly
  table_schema:
    columns:
    - name: app_id
      type: INTEGER
    - name: crawled_at
      type: TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d', 'now', 'localtime'))
    indexes:
    - name: idx_uk_taptap_pc_hot_list_ids_hourly_crawled_at_app_id
      columns: [crawled_at, app_id]
      unique: true
  parser:
    type: json
    root_path: "data.list" 
    fields:
    - name: app_id
      path: id
      to_number: true
retry:
  backoff_base: 2.0
  max_attempts: 3
anti_spider:
  enabled: false
