name: TaptapPC热门游戏统计数据采集任务
type: api
method: GET
trigger_type: user
iterate:
- var_name: app_id
  values:
  - 6974
  - 7054
  - 10056
  - 45213
  - 58881
  - 58885
  - 70253
  - 78938
  - 82921
  - 84463
  - 130651
  - 139301
  - 145396
  - 146791
  - 161414
  - 168332
  - 172664
  - 176228
  - 176733
  - 177804
  - 188212
  - 188743
  - 190930
  - 191385
  - 192675
  - 195928
  - 202416
  - 202514
  - 203729
  - 207018
  - 209866
  - 213181
  - 214603
  - 218210
  - 219503
  - 221380
  - 221583
  - 222089
  - 223632
  - 224267
  - 226568
  - 229966
  - 231537
  - 232326
  - 233514
  - 233558
  - 234280
  - 234493
  - 236627
  - 238517
  - 239372
  - 241042
  - 242904
  - 243110
  - 247283
  - 273365
  - 281223
  - 305435
  - 330259
  - 337799
  - 352408
  - 382756
  - 383413
  - 387264
  - 388717
  - 524022
  - 550307
  - 613799
  - 617522
  - 622867
  - 708799
  - 708927
  - 711932
  - 712207
  - 714119
  - 714123
  - 719426
  - 719781
  - 723266
  - 732013
  - 733498
  - 733908
  - 737341
  - 737825
  - 741793
  - 744415
  - 746164
  - 747914
  - 748031
  - 749379
  - 751890
  - 751902
  - 751906
  - 751919
  - 752178
  - 752573
  - 752978
  - 755439
  - 755604
  - 759688
  - 759941
  - 760944
  - 766061
  - 768687
  - 771648
  - 772303
  - 774226
  - 775179
  - 820664
  - 840947
request_interval: 2
url: https://www.taptap.cn/webapiv2/review/v2/list-by-app?app_id={app_id}&limit=1&sort=hot&stage_type=1&X-UA=V%3D1%26PN%3DWebApp%26LANG%3Dzh_CN%26VN_CODE%3D100000000%26LOC%3DCN%26PLT%3DPC%26DS%3DPC%26UID%3D9a6ce663-b36b-4427-a991-b59918a2bd0b%26OS%3DWindows%26OSV%3D10%26DT%3DPC
outputs:
- target_table: taptap_hot_list_game_hourly
  table_schema:
    columns:
    - constraint: PRIMARY KEY AUTOINCREMENT
      name: id
      type: INTEGER
    - name: app_id
      type: INTEGER
    - name: app_name
      type: TEXT
    - name: released_time
      type: INTEGER
    - name: pc_download_count
      type: INTEGER
    - name: hits_total
      type: INTEGER
    - name: hits_total_val
      type: INTEGER
    - name: fans_count
      type: INTEGER
    - name: review_count
      type: INTEGER
    - name: wish_count
      type: INTEGER
    - name: topic_count
      type: INTEGER
    - name: official_topic_count
      type: INTEGER
    - name: crawled_at
      type: TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H', 'now', 'localtime'))
    indexes:
    - columns:
      - app_id
      - crawled_at
      name: idx_uk_app_id_crawled_at
      unique: true
  parser:
    type: json
    root_path: data.list
    fields:
    - name: released_time
      path: moment.app.released_time
      to_number: true
    - name: app_id
      path: moment.app.id
      to_number: true
    - name: app_name
      path: moment.app.title
    - name: pc_download_count
      path: moment.app.stat.pc_download_count
      to_number: true
    - name: hits_total
      path: moment.app.stat.hits_total
      to_number: true
    - name: hits_total_val
      path: moment.app.stat.hits_total_val
      to_number: true
    - name: fans_count
      path: moment.app.stat.fans_count
      to_number: true
    - name: review_count
      path: moment.app.stat.review_count
      to_number: true
    - name: wish_count
      path: moment.app.stat.wish_count
      to_number: true
    - name: topic_count
      path: moment.app.stat.topic_count
      to_number: true
    - name: official_topic_count
      path: moment.app.stat.official_topic_count
      to_number: true
retry:
  backoff_base: 2.0
  max_attempts: 3
anti_spider:
  enabled: false
